
version: '3.2'

volumes:
  dbdata:
    driver: local

services:
  db:
    image: postgres:11
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata

  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      RACK_ENV: ${STAGE}
      RAILS_ENV: ${STAGE}
      WEBPACKER_DEV_SERVER_HOST: webpack
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - webpack
    tty: true
    stdin_open: true

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: ${STAGE}
      RAILS_ENV: ${STAGE}
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
