default:
  navigation:
    - title: Blog
      url: /blog
    - title: Klamotten
      subtitle: Kategorien
      url: /t/klamotten
      items:
        - :title: T-Shirts
          :url: /t/klamotten/t-shirts
        - :title: Pullover
          :url: /t/klamotten/pullover
        - :title: Beenies
          :url: /t/klamotten/beenies
      promo_banners:
        - subtitle: New collection
          title: Summer 2021
          url: /t/klamotten/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Prints
      url: /t/prints
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    # - title: Accessoires
    #   url: /accessoires
    #   subtitle: Kategorien
    #   items:
    #     - :title: Beutel
    #       :url: /accessoires/beutel
    #   promo_banners:
    #     - subtitle: New collection
    #       title: Summer 2019
    #       url: /t/new-collection/summer-2019
    #       image: 'meganav/promo_banner_left-second-category.jpg'
    #     - subtitle: Special Offers
    #       title: Get up to 30% off
    #       url: /t/special-offers/30-off
    #       image: 'meganav/promo_banner_right-second-category.jpg'
